name: fun_with_flutter
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  rxdart: ^0.22.0
  bloc: ^0.15.0
  equatable: ^0.5.0
  flutter_bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: flutter_web
  animated_text_kit:
    git:
      url: https://github.com/funwithflutter/Animated-Text-Kit

dev_dependencies:
  build_runner: ^1.6.7
  build_web_compilers: ^2.2.3
  pedantic: ^1.8.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
